# fly.toml app configuration file generated for dkmt-vite-late-sea-1887 on 2023-11-15T19:56:54-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dkmt-vite-late-sea-1887"
primary_region = "bog"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
